name: Generate Snake Animation

permissions:
  contents: write

on:
  workflow_dispatch:  # Permite executar manualmente
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente às 00:00 UTC (21h no Brasil)

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante acesso completo ao histórico de commits

      - name: Remover animação antiga (opcional, mas ajuda com cache)
        run: rm -f dist/github-contribution-grid-snake.svg

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: marciocleydev
          svg_out_path: dist/github-contribution-grid-snake.svg
          color_snake: '#FF8C00'
          color_dots: '#013220,#026440,#03AC13,#32CD32'

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution snake"
          add: "dist/github-contribution-grid-snake.svg"
          default_author: github_actions
          push: true
