name: Generate Snake Animation

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remover animação antiga
        run: rm -f dist/github-contribution-grid-snake.svg

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: marciocleydev
          outputs: dist/github-contribution-grid-snake.svg?color_snake=%23FF8C00&color_dots=%23013220,%23026440,%2303AC13,%2332CD32

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution snake"
          add: "dist/github-contribution-grid-snake.svg"
          default_author: github_actions
          push: true
