name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # roda todos os dias à meia-noite

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: marciocleydev
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution snake"
          add: "dist/github-contribution-grid-snake.svg"
